services:
  ffserver:
    image: detifm-ffserver
    build: ffserver/.

  web:
    image: httpd:2.4.54
    ports:
      - "80:80"
    volumes:
      - "./web/httpd.conf:/usr/local/apache2/conf/httpd.conf:ro"
      - "./web/prg/:/usr/local/apache2/conf/prg/:ro"
