services:
  ffserver:
    image: detifm-ffserver
    build: ffserver/.
    volumes:
      - "./ffserver/ffserver.conf:/etc/ffserver.conf:ro"


  web:
    image: httpd:2.4.54
    ports:
      - "80:80"
    volumes:
      - "./web/httpd.conf:/usr/local/apache2/conf/httpd.conf:ro"
      - "./web/etc/:/usr/local/apache2/conf/etc/:ro"
